nohup: ignoring input
Wavefunction build complete.
M1=10.889  M2=10.889  M3=10.1531  M4=10.1531
m1=4.23
From KernelObject[28, local]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        -7
NIntegrate::eincr: The global error of the strategy GlobalAdaptive has increased more than 2000 times. The global error is expected to decrease monotonically after a number of integrand evaluations. Suspect one of the following: the working precision is insufficient for the specified precision goal; the integrand is highly oscillatory or it is not a (piecewise) smooth function; or the true value of the integral is 0. Increasing the value of the GlobalAdaptive option MaxErrorIncreases might lead to a convergent numerical integration. NIntegrate obtained -0.0420843 and 4.18348 10   for the integral and error estimates.
From KernelObject[28, local]:
                                                                                                                                                                                                                                                         -7
NIntegrate::ncvb: NIntegrate failed to converge to prescribed accuracy after 200 recursive bisections in OneFlavour`Private`x near {OneFlavour`Private`x, OneFlavour`Private`y} = {0.0000978614, 0.728938}. NIntegrate obtained -0.0420781 and 2.36446 10   for the integral and error estimates.
From KernelObject[28, local]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       -7
NIntegrate::eincr: The global error of the strategy GlobalAdaptive has increased more than 2000 times. The global error is expected to decrease monotonically after a number of integrand evaluations. Suspect one of the following: the working precision is insufficient for the specified precision goal; the integrand is highly oscillatory or it is not a (piecewise) smooth function; or the true value of the integral is 0. Increasing the value of the GlobalAdaptive option MaxErrorIncreases might lead to a convergent numerical integration. NIntegrate obtained -0.131131 and 4.07578 10   for the integral and error estimates.
From KernelObject[28, local]:
                                                                                                                                                                                                                                                      -7
NIntegrate::ncvb: NIntegrate failed to converge to prescribed accuracy after 200 recursive bisections in OneFlavour`Private`x near {OneFlavour`Private`x, OneFlavour`Private`y} = {0.000107576, 0.54952}. NIntegrate obtained -0.131124 and 2.70851 10   for the integral and error estimates.
From KernelObject[29, local]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      -7
NIntegrate::eincr: The global error of the strategy GlobalAdaptive has increased more than 2000 times. The global error is expected to decrease monotonically after a number of integrand evaluations. Suspect one of the following: the working precision is insufficient for the specified precision goal; the integrand is highly oscillatory or it is not a (piecewise) smooth function; or the true value of the integral is 0. Increasing the value of the GlobalAdaptive option MaxErrorIncreases might lead to a convergent numerical integration. NIntegrate obtained 0.141637 and 4.32018 10   for the integral and error estimates.
From KernelObject[29, local]:
                                                                                                                                                                                                                                                      -7
NIntegrate::ncvb: NIntegrate failed to converge to prescribed accuracy after 200 recursive bisections in OneFlavour`Private`x near {OneFlavour`Private`x, OneFlavour`Private`y} = {0.000109251, 0.554034}. NIntegrate obtained 0.141642 and 2.94204 10   for the integral and error estimates.
From KernelObject[28, local]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       -7
NIntegrate::eincr: The global error of the strategy GlobalAdaptive has increased more than 2000 times. The global error is expected to decrease monotonically after a number of integrand evaluations. Suspect one of the following: the working precision is insufficient for the specified precision goal; the integrand is highly oscillatory or it is not a (piecewise) smooth function; or the true value of the integral is 0. Increasing the value of the GlobalAdaptive option MaxErrorIncreases might lead to a convergent numerical integration. NIntegrate obtained -0.217133 and 9.10805 10   for the integral and error estimates.
From KernelObject[28, local]:
                                                                                                                                                                                                                                                        -6
NIntegrate::ncvb: NIntegrate failed to converge to prescribed accuracy after 200 recursive bisections in OneFlavour`Private`x near {OneFlavour`Private`x, OneFlavour`Private`y} = {0.000154247, 0.0413385}. NIntegrate obtained -0.217128 and 1.39734 10   for the integral and error estimates.
From KernelObject[29, local]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       -7
NIntegrate::eincr: The global error of the strategy GlobalAdaptive has increased more than 2000 times. The global error is expected to decrease monotonically after a number of integrand evaluations. Suspect one of the following: the working precision is insufficient for the specified precision goal; the integrand is highly oscillatory or it is not a (piecewise) smooth function; or the true value of the integral is 0. Increasing the value of the GlobalAdaptive option MaxErrorIncreases might lead to a convergent numerical integration. NIntegrate obtained 0.0491742 and 3.21382 10   for the integral and error estimates.
From KernelObject[29, local]:
                                                                                                                                                                                                                                                        -7
NIntegrate::ncvb: NIntegrate failed to converge to prescribed accuracy after 200 recursive bisections in OneFlavour`Private`x near {OneFlavour`Private`x, OneFlavour`Private`y} = {0.0000984146, 0.731923}. NIntegrate obtained 0.0491794 and 1.75709 10   for the integral and error estimates.
End
992.61user 9.74system 0:53.60elapsed 1870%CPU (0avgtext+0avgdata 127252maxresident)k
0inputs+11992outputs (0major+2071121minor)pagefaults 0swaps
