nohup: ignoring input
Wavefunction build complete.
M1=10.889  M2=10.889  M3=9.10387  M4=9.10387
m1=4.23
From KernelObject[21, local]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       -8
NIntegrate::eincr: The global error of the strategy GlobalAdaptive has increased more than 2000 times. The global error is expected to decrease monotonically after a number of integrand evaluations. Suspect one of the following: the working precision is insufficient for the specified precision goal; the integrand is highly oscillatory or it is not a (piecewise) smooth function; or the true value of the integral is 0. Increasing the value of the GlobalAdaptive option MaxErrorIncreases might lead to a convergent numerical integration. NIntegrate obtained -0.0133378 and 6.4486 10   for the integral and error estimates.
From KernelObject[21, local]:
                                                                                                                                                                                                                                                                                                                                                                            -8
NIntegrate::ncvb: NIntegrate failed to converge to prescribed accuracy after 200 recursive bisections in OneFlavour`Private`y near {OneFlavour`Private`x, OneFlavour`Private`y} = {0.333134977511541024675837189285755744381746211068501293640290557621, 0.99999289243445360814335867709443303507285984962892806284508361446}. NIntegrate obtained -0.0133359 and 3.39268 10   for the integral and error estimates.
From KernelObject[21, local]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       -7
NIntegrate::eincr: The global error of the strategy GlobalAdaptive has increased more than 2000 times. The global error is expected to decrease monotonically after a number of integrand evaluations. Suspect one of the following: the working precision is insufficient for the specified precision goal; the integrand is highly oscillatory or it is not a (piecewise) smooth function; or the true value of the integral is 0. Increasing the value of the GlobalAdaptive option MaxErrorIncreases might lead to a convergent numerical integration. NIntegrate obtained 0.0269728 and 2.93692 10   for the integral and error estimates.
From KernelObject[21, local]:
                                                                                                                                                                                                                                                                                                                                                                           -8
NIntegrate::ncvb: NIntegrate failed to converge to prescribed accuracy after 200 recursive bisections in OneFlavour`Private`y near {OneFlavour`Private`x, OneFlavour`Private`y} = {0.331428461881407645944784221649269439510445931305982524749210531666, 0.99999333194283188835152351896587430424290232622297480702400207520}. NIntegrate obtained 0.0269755 and 5.74143 10   for the integral and error estimates.
End
914.46user 9.89system 1:17.28elapsed 1196%CPU (0avgtext+0avgdata 136708maxresident)k
0inputs+11280outputs (0major+1793827minor)pagefaults 0swaps
